services:
  shai-test:
    build: .
    container_name: shai-test-env
    volumes:
      - /Users/hades:/Users/hades
    environment:
      - CONTAINER_NAME=shai-test-env
    working_dir: /Users/hades
    stdin_open: true
    tty: true
    command: /bin/zsh
