format = """
${env_var.CONTAINER_NAME}$directory$git_branch$git_status$python$java$docker_context
$character"""

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = "!${count}"
untracked = "?${count}"
staged = "+${count}"

[python]
symbol = "🐍 "
format = "via [${symbol}${version}](yellow) "

[java]
symbol = "☕ "
format = "via [${symbol}${version}](red bold) "

[docker_context]
symbol = "🐳 "
format = "via [${symbol}${context}](blue bold) "
only_with_files = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[env_var.CONTAINER_NAME]
variable = "CONTAINER_NAME"
symbol = "🐳 "
format = "[$symbol<$env_value>]($style) "
style = "bold yellow"
